# src/sbsys/errors.py
"""Exception hierarchy for the SBSYS client.

Everything raised by this package inherits from :class:`SbsysError`, so callers
can catch a single type and never have to know that ``httpx`` is used
underneath. HTTP failures are translated into these types by the transport
layer; ``httpx.HTTPStatusError`` never escapes the package.
"""

from __future__ import annotations


class SbsysError(Exception):
    """Base class for every exception raised by this package."""


class SbsysValidationError(SbsysError):
    """Raised when input fails local validation before a request is sent.

    Used for problems we can detect without talking to SBSYS, such as a
    malformed CPR number or an empty case title. Error messages deliberately
    omit the offending value, because it is often personal data.
    """


class SbsysAPIError(SbsysError):
    """Raised when SBSYS returns an unsuccessful HTTP response.

    Attributes:
        status_code: HTTP status returned by SBSYS, or ``0`` if the request
            never completed (connection error, DNS failure, timeout).
        method: HTTP method of the failed request.
        url: Path or absolute URL of the failed request.
        body: Response body, redacted and truncated to 2000 characters. SBSYS
            often puts the only usable explanation of a ``400`` in here. It may
            contain personal data echoed back from the rejected request, so log
            it only while debugging, never to a shared log index.
        request_id: Correlation id generated by this client, also written to
            the debug log, so a report from a user can be traced to a request.
    """

    def __init__(
        self,
        status_code: int,
        method: str,
        url: str,
        body: str | None = None,
        request_id: str | None = None,
    ) -> None:
        """Build the exception and render a human-readable message.

        Args:
            status_code: HTTP status, or ``0`` when no response was received.
            method: HTTP method of the failed request.
            url: Path or absolute URL of the failed request.
            body: Redacted response body, if any.
            request_id: Correlation id for the failed request.
        """
        self.status_code = status_code
        self.method = method
        self.url = url
        self.body = body
        self.request_id = request_id
        detail = f" — {body[:500]}" if body else ""
        rid = f" [request-id {request_id}]" if request_id else ""
        super().__init__(f"{method} {url} returned {status_code}{rid}{detail}")


class SbsysAuthError(SbsysAPIError):
    """Raised on ``401``/``403``, or when an access token cannot be obtained.

    A single ``401`` on a normal request does not surface as this error: the
    auth layer refreshes the token and retries once first. Seeing this means
    the credentials themselves are wrong, expired, or lack the permission the
    endpoint requires.
    """


class SbsysNotFoundError(SbsysAPIError):
    """Raised on ``404``, and when a search endpoint returns no match.

    Search endpoints answer ``200`` with an empty result set rather than
    ``404``. Resource methods that promise exactly one object, such as
    :meth:`~sbsys.resources.parter.Parter.hent_person`, translate that empty
    result into this error so callers get one consistent failure mode.
    """


class SbsysConflictError(SbsysAPIError):
    """Raised on ``409``, when the request conflicts with the current state.

    Typically an attempt to modify a closed case, or to create something that
    already exists. Retrying without changing anything will not help.
    """


class SbsysServerError(SbsysAPIError):
    """Raised on ``5xx``. Retried automatically on idempotent requests."""


class SbsysRateLimitError(SbsysAPIError):
    """Raised on ``429``. Retried automatically on idempotent requests."""


def error_for_status(
    status_code: int,
    method: str,
    url: str,
    body: str | None = None,
    request_id: str | None = None,
) -> SbsysAPIError:
    """Map an HTTP status code to the matching exception type.

    Args:
        status_code: HTTP status returned by SBSYS.
        method: HTTP method of the failed request.
        url: Path or absolute URL of the failed request.
        body: Redacted response body, if any.
        request_id: Correlation id for the failed request.

    Returns:
        An instance of the most specific :class:`SbsysAPIError` subclass for
        the status. Unrecognised statuses fall back to :class:`SbsysAPIError`
        itself, so an unexpected code is still a catchable SBSYS error rather
        than something leaking out of ``httpx``.
    """
    cls: type[SbsysAPIError]
    if status_code in (401, 403):
        cls = SbsysAuthError
    elif status_code == 404:
        cls = SbsysNotFoundError
    elif status_code == 409:
        cls = SbsysConflictError
    elif status_code == 429:
        cls = SbsysRateLimitError
    elif status_code >= 500:
        cls = SbsysServerError
    else:
        cls = SbsysAPIError
    return cls(status_code, method, url, body, request_id)
